services:
  dev:
    image: ml-template:0.0.0
    command: sleep infinity
    volumes:
      - type: bind
        source: .
        target: /home/vscode/workspaces
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
