services:
  dev:
    build:
      context: .
    command: sleep infinity
    volumes:
      - type: bind
        source: .
        target: /home/vscode/workspaces
    shm_size: "2gb" # 共有メモリがないとこけるので大きくする
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
